name: dream-app-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deployment to VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh_key
          chmod 600 ssh_key

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key root@139.59.45.219 << 'EOF'
           # Load NVM (IMPORTANT FIX)
            export NVM_DIR="/root/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 24

            
            cd dream-app

            git reset --hard
            git clean -fd
            git pull

            # BACKEND
            cd backend
            /root/.nvm/versions/node/v24.11.1/bin/npm install
            /root/.nvm/versions/node/v24.11.1/bin/npm run build
            DATABASE_URL='${{ secrets.DATABASE_URL }}' \
            JWT_SECRET='${{ secrets.JWT_SECRET }}' \
            /root/.nvm/versions/node/v24.11.1/bin/pm2 restart dream-backend

            # FRONTEND
            cd ../frontend
            /root/.nvm/versions/node/v24.11.1/bin/npm install
            /root/.nvm/versions/node/v24.11.1/bin/npm run build
            /root/.nvm/versions/node/v24.11.1/bin/pm2 restart dream-frontend
          EOF
