name: ci_frontend

on: 
  push:
   branches:
     - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: dillax/dream-frontend:${{ github.sha }}
          
      - name: Deploy Frontend
        run: |
          echo "${{ secrets.SSH_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@139.59.84.87 \
            IMAGE="dillax/dream-frontend:${GITHUB_SHA}" \
            CONTAINER="dream-frontend" \
            << 'EOF'

            docker rm -f "$CONTAINER" || true
            docker pull "$IMAGE"

            docker run -d \
              --name "$CONTAINER" \
              -p 127.0.0.1:3001:80 \
              -p 127.0.0.1:3001:443 \
              "$IMAGE"

          EOF
